/* Simulated 2D water with a separate, continuous reveal envelope. */
(() => {
  const clamp=(x,a=0,b=1)=>Math.max(a,Math.min(b,x));
  const smooth=(a,b,x)=>{const t=clamp((x-a)/(b-a));return t*t*(3-2*t);};
  function playbackClock(meta) {
    const keys=meta.playback?.keys;
    if(!keys)return p=>p;
    const slopes=keys.slice(1).map(([time,progress],i)=>(progress-keys[i][1])/(time-keys[i][0]));
    // Monotone cubic timing changes speed smoothly without pausing at phase joins.
    const tangent=keys.map((_,i)=>{
      if(!i)return slopes[0];if(i===keys.length-1)return slopes[i-1];
      const before=keys[i][0]-keys[i-1][0],after=keys[i+1][0]-keys[i][0];
      const a=2*after+before,b=after+2*before;
      return (a+b)/(a/slopes[i-1]+b/slopes[i]);
    });
    return progress=>{
      const time=progress*meta.durationMs;
      let i=0;while(i<keys.length-2&&time>keys[i+1][0])i++;
      const span=keys[i+1][0]-keys[i][0],t=clamp((time-keys[i][0])/span),t2=t*t,t3=t2*t;
      return clamp((2*t3-3*t2+1)*keys[i][1]+(t3-2*t2+t)*span*tangent[i]
        +(-2*t3+3*t2)*keys[i+1][1]+(t3-t2)*span*tangent[i+1]);
    };
  }
  let prepared;
  function prepare() {
    if(!prepared)prepared=(async()=>{
      const base=new URL('assets/menu/wave-physics/',document.baseURI);
      const response=await fetch(new URL('fluid-meta.json',base),{cache:'no-cache'});
      if(!response.ok)throw new Error('Water motion metadata unavailable');
      const meta=await response.json();
      const data=await fetch(new URL(meta.positions,base));
      if(!data.ok)throw new Error('Water motion frames unavailable');
      const buffer=await data.arrayBuffer();
      let positions;
      if(meta.encoding==='uint16') {
        const encoded=new Uint16Array(buffer);positions=new Float32Array(encoded.length);
        for(let n=0;n<encoded.length;n++)positions[n]=meta.bounds[n%2]+encoded[n]*(meta.bounds[n%2+2]-meta.bounds[n%2])/65535;
      } else positions=new Float32Array(buffer);
      let contact=null;
      if(meta.contact) {
        const response=await fetch(new URL(meta.contact.file,base));
        if(!response.ok)throw new Error('Water contact data unavailable');
        const buffer=await response.arrayBuffer();
        if(meta.contact.encoding==='uint16') {
          const bytes=new Uint16Array(buffer);contact=new Float32Array(bytes.length);
          for(let i=0;i<bytes.length;i++)contact[i]=bytes[i]===65535?Infinity:bytes[i]/65534;
        } else contact=new Float32Array(buffer);
        if(contact.length!==meta.contact.width*meta.contact.height)throw new Error('Incomplete water contact data');
      }
      if(positions.length!==meta.frameCount*meta.particleCount*2)throw new Error('Incomplete water motion');
      // Foam is generated by simulated acceleration at impacts and decays with each parcel.
      const foam=new Uint8Array(meta.frameCount*meta.particleCount),N=meta.particleCount,F=meta.fps;
      for(let f=1;f<meta.frameCount-1;f++)for(let i=0;i<N;i++) {
        const k=(f*N+i)*2,b=k-N*2,n=k+N*2;
        const ax=(positions[n]-2*positions[k]+positions[b])*F*F;
        const ay=(positions[n+1]-2*positions[k+1]+positions[b+1])*F*F+9.81;
        const impact=clamp((Math.hypot(ax,ay)-24)/125);
        foam[f*N+i]=Math.round(Math.max(impact*255,foam[(f-1)*N+i]*Math.exp(-1/F/.64)));
      }
      let drying=null;
      if(meta.drying&&contact) {
        const spec=meta.drying;
        const buffers=await Promise.all([spec.zone,spec.direct].map(async file=>{
          const result=await fetch(new URL(file,base));
          if(!result.ok)throw new Error('Localized water data unavailable');
          return result.arrayBuffer();
        }));
        const zone=new Uint8Array(buffers[0]),encoded=new Uint16Array(buffers[1]);
        if(zone.length!==contact.length||encoded.length!==contact.length)throw new Error('Incomplete localized water data');
        const direct=Float32Array.from(encoded,v=>v===65535?Infinity:v/65534);
        const W=meta.contact.width,H=meta.contact.height,rank=new Float32Array(zone.length);
        // Distance from an already washed edge makes the remaining film recede
        // in irregular islands, instead of fading a rectangular piece of paper.
        for(let y=0;y<H;y++)for(let x=0;x<W;x++) {
          const i=y*W+x;
          rank[i]=zone[i]&&direct[i]>spec.start?Math.min(x?rank[i-1]+1:1,y?rank[i-W]+1:1000,(x&&y)?rank[i-W-1]+1.414:1000):0;
        }
        let largest=1;
        for(let y=H-1;y>=0;y--)for(let x=W-1;x>=0;x--) {
          const i=y*W+x;if(!rank[i])continue;
          rank[i]=Math.min(rank[i],x<W-1?rank[i+1]+1:1,y<H-1?rank[i+W]+1:1,(x<W-1&&y<H-1)?rank[i+W+1]+1.414:1000);
        }
        for(let i=0;i<rank.length;i++) {
          const x=i%W,y=Math.floor(i/W);
          rank[i]*=1+.2*Math.sin(x*.47+y*.23)+.12*Math.sin(x*.21-y*.61);
          largest=Math.max(largest,rank[i]);
        }
        for(let i=0;i<rank.length;i++)rank[i]=spec.start+(spec.end-spec.start)*rank[i]/largest;
        const cells=[];for(let i=0;i<zone.length;i++)if(zone[i])cells.push(i);
        drying={zone,direct,rank,cells};
      }
      return {meta,positions,foam,contact,drying};
    })().catch(error=>{prepared=null;throw error;});
    return prepared;
  }
  class MenuWave {
    static prepare(){return prepare();}
    static separationDelay(duration){return duration*.28;}
    static async create(stage,pages,direction=1,previousPages=[]) {
      const assets=await prepare(),renderer=new MenuWave(stage,pages,direction,assets,previousPages);
      try {
        await Promise.all([...renderer.spread.querySelectorAll('img'),...renderer.previousPages].map(img=>img.decode()));
        renderer.draw(0);stage.appendChild(renderer.element);return renderer;
      }catch(error){renderer.dispose();throw error;}
    }
    constructor(stage,pages,direction,assets,previousPages) {
      this.stage=stage;this.assets=assets;this.direction=direction<0?-1:1;
      this.simulationProgress=playbackClock(assets.meta);
      this.element=document.createElement('div');this.element.className='menu-book-wave';
      this.element.setAttribute('aria-hidden','true');this.element.inert=true;
      this.element.dataset.direction=this.direction>0?'next':'previous';
      this.spread=document.createElement('div');this.spread.className='menu-book-wave-spread';this.spread.style.visibility='hidden';
      pages.forEach((source,index)=>{
        const page=document.createElement('div');page.className=`menu-book-wave-page menu-book-wave-page--${index?'right':'left'}`;
        const img=new Image();img.src=source.currentSrc||source.src;img.alt='';img.draggable=false;page.appendChild(img);this.spread.appendChild(page);
      });
      this.canvas=document.createElement('canvas');this.canvas.className='menu-book-wave-canvas';
      this.canvas.setAttribute('aria-hidden','true');this.context=this.canvas.getContext('2d',{alpha:true});
      this.fluid=document.createElement('canvas');this.wet=document.createElement('canvas');
      this.view=assets.meta.viewport||{x:2.5,y:0,width:9.5,height:9.5*741/900};
      this.gw=stage.getBoundingClientRect().width<700?224:288;this.gh=Math.round(this.gw*this.view.height/this.view.width);
      const sigma=assets.meta.spacing*this.gw/this.view.width*.72;
      this.kernelRadius=Math.ceil(sigma*2.4);this.kernelWidth=this.kernelRadius*2+1;
      const R=this.kernelRadius,K=this.kernelWidth;this.kernels=[];
      for(let fy=0;fy<16;fy++)for(let fx=0;fx<16;fx++) {
        const kernel=new Float32Array(K*K);
        for(let dy=-R;dy<=R;dy++)for(let dx=-R;dx<=R;dx++){
          const rr=(dx+.5-fx/16)**2+(dy+.5-fy/16)**2;
          kernel[(dy+R)*K+dx+R]=rr>R*R?0:Math.exp(-rr/(2*sigma*sigma));
        }
        this.kernels.push(kernel);
      }
      this.fluid.width=this.gw;this.fluid.height=this.gh;
      this.wet.width=assets.meta.contact?.width||this.gw;this.wet.height=assets.meta.contact?.height||this.gh;
      this.fluidContext=this.fluid.getContext('2d');this.wetContext=this.wet.getContext('2d');
      this.fluidPixels=this.fluidContext.createImageData(this.gw,this.gh);
      this.wetPixels=this.wetContext.createImageData(this.wet.width,this.wet.height);
      this.previousPages=previousPages.map(source=>{const img=new Image();img.src=source.currentSrc||source.src;return img;});
      if(assets.drying) {
        this.filmMask=document.createElement('canvas');this.filmMask.width=this.wet.width;this.filmMask.height=this.wet.height;
        this.filmMaskContext=this.filmMask.getContext('2d');
        this.filmPixels=this.filmMaskContext.createImageData(this.wet.width,this.wet.height);
        this.filmRim=document.createElement('canvas');this.filmRim.width=this.wet.width;this.filmRim.height=this.wet.height;
        this.rimContext=this.filmRim.getContext('2d');this.rimPixels=this.rimContext.createImageData(this.wet.width,this.wet.height);
        this.film=document.createElement('canvas');this.oldSpread=document.createElement('canvas');
        this.filmContext=this.film.getContext('2d');this.oldContext=this.oldSpread.getContext('2d');
      }
      this.density=new Float32Array(this.gw*this.gh);this.kinetic=new Float32Array(this.gw*this.gh);
      this.contact=new Uint8Array(this.gw*this.gh);this.lastP=-1;
      this.depth=new Float32Array(this.gw*this.gh);
      // Water color only: broad lighting bands are evaluated once per row/column.
      this.waterLightX=new Float32Array(this.gw);this.waterLightY=new Float32Array(this.gh);
      this.sampled=new Float32Array(assets.meta.particleCount*4);
      this.particleOpacity=new Float32Array(assets.meta.particleCount);this.particleOpacity.fill(1);
      this.absorbedAt=new Float32Array(assets.meta.particleCount);this.absorbedAt.fill(-1);
      this.absorbedParticles=0;this.dominantWaves=[];this.underlaySource=null;
      this.bodyMask=new Uint8Array(this.gw*this.gh);
      this.previousBodyMask=new Uint8Array(this.gw*this.gh);
      this.sweptBodyMask=new Uint8Array(this.gw*this.gh);
      this.previousPositions=new Float32Array(assets.meta.particleCount*2);
      this.bodyVisited=new Uint8Array(this.gw*this.gh);
      this.bodyQueue=new Int32Array(this.gw*this.gh);
      if(assets.contact&&assets.meta.contact.kind==='continuous-envelope') {
        const arrivals=assets.contact,W=assets.meta.contact.width;
        this.arrivalSlope=new Float32Array(arrivals.length);
        for(let i=0;i<arrivals.length;i++) {
          const x=i%W,left=x?i-1:i,right=x<W-1?i+1:i;
          this.arrivalSlope[i]=(arrivals[right]-arrivals[left])/(right-left||1);
        }
      }
      this.element.append(this.spread,this.canvas);
    }
    setDominantWaves(renderers) {
      this.dominantWaves=renderers.filter(renderer=>renderer!==this&&renderer.direction!==this.direction);
      for(const renderer of this.dominantWaves) {
        renderer.hasFollowers=true;
        renderer.updateBodyMask();
        renderer.sweptBodyMask.set(renderer.bodyMask);
      }
    }
    setUnderlaySource(canvas) { this.underlaySource=canvas; }
    updateBodyMask() {
      // Contact needs a connected sheet, not isolated leading spray. Build the
      // same physical body in the renderer's unmirrored simulation coordinates.
      const W=this.gw,H=this.gh,d=this.density,seen=this.bodyVisited,mask=this.bodyMask,q=this.bodyQueue;
      seen.fill(0);mask.fill(0);
      for(let start=0;start<d.length;start++) {
        if(seen[start]||d[start]<1.12)continue;
        let head=0,tail=1,minX=W,maxX=0,minY=H,maxY=0;
        q[0]=start;seen[start]=1;
        while(head<tail) {
          const cell=q[head++],x=cell%W,y=Math.floor(cell/W);
          minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,y);maxY=Math.max(maxY,y);
          if(x>0){const n=cell-1;if(!seen[n]&&d[n]>=1.12){seen[n]=1;q[tail++]=n;}}
          if(x<W-1){const n=cell+1;if(!seen[n]&&d[n]>=1.12){seen[n]=1;q[tail++]=n;}}
          if(y>0){const n=cell-W;if(!seen[n]&&d[n]>=1.12){seen[n]=1;q[tail++]=n;}}
          if(y<H-1){const n=cell+W;if(!seen[n]&&d[n]>=1.12){seen[n]=1;q[tail++]=n;}}
        }
        if(tail<48||Math.max(maxX-minX,maxY-minY)<12)continue;
        for(let i=0;i<tail;i++)mask[q[i]]=1;
      }
    }
    touchesDominant(x,y,previousX,previousY) {
      const steps=Math.min(96,Math.max(1,Math.ceil(Math.hypot(x-previousX,y-previousY)*2)));
      for(const newer of this.dominantWaves) {
        if(newer.disposed||newer.lastP<0)continue;
        for(let step=0;step<=steps;step++) {
          const t=step/steps;
          const px=previousX+(x-previousX)*t,py=previousY+(y-previousY)*t;
          const screenX=this.direction<0?1-px/this.gw:px/this.gw;
          const nx=Math.floor((newer.direction<0?1-screenX:screenX)*newer.gw);
          const ny=Math.floor(py/this.gh*newer.gh);
          if(nx>=0&&nx<newer.gw&&ny>=0&&ny<newer.gh&&newer.sweptBodyMask[ny*newer.gw+nx])return true;
        }
      }
      return false;
    }
    sweepBody() {
      // Cover the newer sheet's travel during this frame too. Otherwise a thin
      // fast sheet could jump across a stationary older parcel on a slow device.
      const W=this.gw,H=this.gh,mask=this.bodyMask,previous=this.previousBodyMask,swept=this.sweptBodyMask;
      for(let i=0;i<mask.length;i++)swept[i]=mask[i]|previous[i];
      if(this.lastP<0)return;
      for(let i=0;i<this.particleOpacity.length;i++) {
        if(!this.particleOpacity[i])continue;
        const x=this.sampled[i*4],y=this.sampled[i*4+1];
        const px=this.previousPositions[i*2],py=this.previousPositions[i*2+1];
        const ix=Math.floor(x),iy=Math.floor(y),pix=Math.floor(px),piy=Math.floor(py);
        const currentBody=ix>=0&&ix<W&&iy>=0&&iy<H&&mask[iy*W+ix];
        const priorBody=pix>=0&&pix<W&&piy>=0&&piy<H&&previous[piy*W+pix];
        if(!currentBody&&!priorBody)continue;
        const steps=Math.min(192,Math.max(1,Math.ceil(Math.hypot(x-px,y-py)*2)));
        for(let k=0;k<=steps;k++) {
          const t=k/steps,cx=Math.floor(px+(x-px)*t),cy=Math.floor(py+(y-py)*t);
          if(cx>=0&&cx<W&&cy>=0&&cy<H)swept[cy*W+cx]=1;
        }
      }
    }
    field(p) {
      const {meta:m,positions:a}=this.assets,n=m.particleCount;
      const t=clamp(p)*(m.frameCount-1),f=Math.floor(t),next=Math.min(m.frameCount-1,f+1),blend=t-f;
      const off=f*n*2,end=next*n*2,W=this.gw,H=this.gh,sx=W/this.view.width,sy=H/this.view.height;
      const field=this.density,energy=this.kinetic;field.fill(0);energy.fill(0);
      if(this.hasFollowers)this.previousBodyMask.set(this.bodyMask);
      const radius=this.kernelRadius,kw=this.kernelWidth;
      for(let i=0;i<n;i++) {
        const j=i*2,x=(a[off+j]*(1-blend)+a[end+j]*blend-this.view.x)*sx;
        const y=H-(a[off+j+1]*(1-blend)+a[end+j+1]*blend-this.view.y)*sy;
        const previousX=this.lastP<0?x:this.sampled[i*4],previousY=this.lastP<0?y:this.sampled[i*4+1];
        if(this.hasFollowers){this.previousPositions[i*2]=previousX;this.previousPositions[i*2+1]=previousY;}
        if(this.absorbedAt[i]<0&&this.dominantWaves.length&&this.touchesDominant(x,y,previousX,previousY)) {
          this.absorbedAt[i]=p;this.absorbedParticles++;
        }
        // Particle identity, rather than a stationary cutout, remembers contact.
        // A short fade merges the old edge into the dominant body; it cannot
        // return when either wave later rebounds or drains away.
        if(this.absorbedAt[i]>=0)this.particleOpacity[i]=Math.min(this.particleOpacity[i],1-smooth(this.absorbedAt[i],this.absorbedAt[i]+.025,p));
        const opacity=this.particleOpacity[i];
        this.sampled[i*4]=x;this.sampled[i*4+1]=y;
        this.sampled[i*4+2]=(a[end+j]-a[off+j])*m.fps;
        this.sampled[i*4+3]=-(a[end+j+1]-a[off+j+1])*m.fps;
        if(!opacity||x<-radius||x>W+radius||y<-radius||y>H+radius)continue;
        const naturalFoam=(this.assets.foam[f*n+i]*(1-blend)+this.assets.foam[next*n+i]*blend)/255;
        // A brief foam highlight softens only the old water's absorbing edge.
        const vel=Math.max(naturalFoam,this.absorbedAt[i]>=0?.65*Math.sin(Math.PI*(1-opacity)):0);
        const ix=Math.floor(x),iy=Math.floor(y);
        const kernel=this.kernels[Math.min(15,Math.floor((y-iy)*16))*16+Math.min(15,Math.floor((x-ix)*16))];
        for(let dy=-radius;dy<=radius;dy++) {
          const yy=iy+dy;if(yy<0||yy>=H)continue;
          for(let dx=-radius;dx<=radius;dx++) {
            const xx=ix+dx;if(xx<0||xx>=W)continue;
            const value=kernel[(dy+radius)*kw+dx+radius]*opacity;if(value===0)continue;const k=yy*W+xx;field[k]+=value;energy[k]+=value*vel;
          }
        }
      }
      if(this.hasFollowers){this.updateBodyMask();this.sweepBody();}
      this.element.dataset.absorbedParticles=String(this.absorbedParticles);
      this.element.dataset.absorbedFraction=(this.absorbedParticles/n).toFixed(4);
    }
    stamp(p,paint) {
      this.field(p);const W=this.gw,H=this.gh,d=this.density,water=this.fluidPixels.data,wet=this.wetPixels.data;
      let contacted=0;this.hasFilm=false;
      const depth=this.depth;
      // Water color only: slow coherent variation, without changing the liquid field.
      const lightX=this.waterLightX,lightY=this.waterLightY;
      if(paint) {
        for(let x=0;x<W;x++)lightX[x]=.55*Math.sin(x*.065-p*11)+.22*Math.sin(x*.14+p*7);
        for(let y=0;y<H;y++)lightY[y]=.23*Math.sin(y*.058-p*8);
      }
      for(let y=0;y<H;y++)for(let x=0;x<W;x++) {
        const i=y*W+x;
        depth[i]=d[i]<.98?0:Math.min(x?depth[i-1]+1:1,y?depth[i-W]+1:1,(x&&y)?depth[i-W-1]+1.414:1);
      }
      for(let y=H-1;y>=0;y--)for(let x=W-1;x>=0;x--) {
        const i=y*W+x;if(depth[i]===0)continue;
        depth[i]=Math.min(depth[i],x<W-1?depth[i+1]+1:1,y<H-1?depth[i+W]+1:1,(x<W-1&&y<H-1)?depth[i+W+1]+1.414:1);
      }
      for(let y=0;y<H;y++)for(let x=0;x<W;x++) {
        const i=y*W+x,v=d[i],pixel=i*4;
        const alpha=Math.round(smooth(.84,1.12,v)*255);
        
        this.contact[i]=Math.max(this.contact[i],alpha);
        if(this.contact[i]>200)contacted++;
        if(!this.assets.contact){wet[pixel]=wet[pixel+1]=wet[pixel+2]=255;wet[pixel+3]=this.contact[i];}
        if(!paint)continue;
        if(alpha===0){water[pixel+3]=0;continue;}
        const dx=d[y*W+Math.min(W-1,x+1)]-d[y*W+Math.max(0,x-1)];
        const dy=d[Math.min(H-1,y+1)*W+x]-d[Math.max(0,y-1)*W+x];
        const speed=this.kinetic[i]/Math.max(.1,v);
        const froth=(1-smooth(1.1,3.0,v))*smooth(.13,.72,speed)*.88;
        // Water color only: blue depths, teal body, turquoise edges and aqua foam.
        const edge=Math.exp(-depth[i]/7),body=Math.exp(-depth[i]/21);
        const band=lightX[x]+lightY[y],light=clamp((dx-dy)*.14,-.18,.24);
        const lift=clamp(light+speed*.075,0,.28);
        const r=8+20*body+38*edge+4*band+42*lift;
        const g=92+60*body+47*edge+13*band+35*lift;
        const b=132+27*body+42*edge+9*band+25*lift;
        water[pixel]=r+(220-r)*froth;water[pixel+1]=g+(245-g)*froth;water[pixel+2]=b+(239-b)*froth;
        water[pixel+3]=Math.round(alpha*(.945-.067*edge));
      }
      if(paint){
        this.fluidContext.putImageData(this.fluidPixels,0,0);
        // Detached spray uses its simulated velocity, with a smaller clean droplet profile.
        const fctx=this.fluidContext,A=this.sampled;
        const size=this.assets.meta.spacing*W/this.view.width;
        fctx.fillStyle='rgba(105,211,214,.89)';
        for(let n=0;n<A.length;n+=4) {
          const opacity=this.particleOpacity[n/4];if(!opacity)continue;
          const xx=A[n],yy=A[n+1],ix=Math.floor(xx),iy=Math.floor(yy);
          if(ix<0||ix>=W||iy<0||iy>=H||d[iy*W+ix]>1.5)continue;
          const speed=Math.hypot(A[n+2],A[n+3]);
          fctx.globalAlpha=opacity;
          fctx.beginPath();fctx.ellipse(xx,yy,size*clamp(.24+speed*.014,.24,.62),size*.19,Math.atan2(A[n+3],A[n+2]),0,Math.PI*2);fctx.fill();
        }
        fctx.globalAlpha=1;
        if(this.assets.contact) {
          contacted=0;
          const mask=this.assets.meta.contact,arrivals=this.assets.contact;
          const feather=mask.kind==='continuous-envelope'?(mask.featherCssPixels||0)*mask.width/Math.max(1,this.width):0;
          for(let i=0;i<this.assets.contact.length;i++) {
            const t=this.assets.contact[i],k=i*4;
            let alpha=t<=p?255:0;
            if(feather&&Number.isFinite(t)) {
              const span=Math.max(.00001,this.arrivalSlope[i]*feather),low=t-span*.5,high=t+span*.5;
              alpha=p<=low?0:p>=high?255:Math.round(smooth(low,high,p)*255);
            }
            if(this.assets.drying) {
              const {zone,direct,rank}=this.assets.drying,z=zone[i]/255;
              if(z) {
                const washed=direct[i]<=p?1:0;
                const dry=smooth(rank[i]-.009,rank[i]+.009,p);
                const local=Math.max(washed,dry);
                alpha=Math.round(alpha*(1-z)+255*z*local);
                const filmStart=this.assets.meta.drying.filmStart;
                const film=z*(1-local)*smooth(filmStart,filmStart+.035,p),pixels=this.filmPixels.data;
                pixels[k]=pixels[k+1]=pixels[k+2]=255;pixels[k+3]=Math.round(255*film);
                if(pixels[k+3])this.hasFilm=true;
              }
            }
            wet[k]=wet[k+1]=wet[k+2]=255;wet[k+3]=alpha;if(alpha)contacted++;
          }
          this.element.dataset.wetCoverage=(contacted/this.assets.contact.length).toFixed(6);
          if(this.filmMask&&this.hasFilm) {
            this.filmMaskContext.putImageData(this.filmPixels,0,0);
            const a=this.filmPixels.data,rim=this.rimPixels.data,FW=this.wet.width,FH=this.wet.height;
            for(const cell of this.assets.drying.cells) {
              const x=cell%FW,y=Math.floor(cell/FW),i=cell*4,alpha=a[i+3]/255;
              if(!alpha){rim[i+3]=0;continue;}
              const dx=(a[(y*FW+Math.min(FW-1,x+1))*4+3]-a[(y*FW+Math.max(0,x-1))*4+3])/255;
              const dy=(a[(Math.min(FH-1,y+1)*FW+x)*4+3]-a[(Math.max(0,y-1)*FW+x)*4+3])/255;
              const light=clamp(.5+(dx-dy)*.65);
              rim[i]=28+210*light;rim[i+1]=134+115*light;rim[i+2]=160+95*light;
              rim[i+3]=Math.round(Math.min(.48,Math.hypot(dx,dy)*.48)*alpha*255);
            }
            this.rimContext.putImageData(this.rimPixels,0,0);
          }
        }
        this.wetContext.putImageData(this.wetPixels,0,0);
      }
      if(!this.assets.contact)this.element.dataset.wetCoverage=(contacted/d.length).toFixed(4);
    }
    resize(){
      const rect=this.stage.getBoundingClientRect();this.width=rect.width;this.height=rect.height;
      this.ratio=Math.min(window.devicePixelRatio||1,1.5);
      this.canvas.width=Math.ceil(this.width*this.ratio);this.canvas.height=Math.ceil(this.height*this.ratio);
      if(this.film) {
        this.film.width=this.oldSpread.width=this.canvas.width;
        this.film.height=this.oldSpread.height=Math.ceil(this.canvas.height*.25);
        const ctx=this.oldContext,w=this.width,h=this.height;
        ctx.setTransform(this.ratio,0,0,this.ratio,0,0);
        ctx.fillStyle='#f5ead4';ctx.fillRect(0,0,w,h*.25);
        this.previousPages.forEach((img,i)=>{
          const size=Math.min(w*.5/img.naturalWidth,h/img.naturalHeight),iw=img.naturalWidth*size,ih=img.naturalHeight*size;
          ctx.drawImage(img,i*w*.5+(w*.5-iw)*.5,(h-ih)*.5,iw,ih);
        });
      }
    }
    drawFilm(p) {
      if(!this.film||!this.hasFilm||this.previousPages.length!==2||p<this.assets.meta.drying.filmStart||p>this.assets.meta.drying.end+.01)return;
      const ctx=this.filmContext,w=this.width,h=this.height,r=this.ratio;
      if(this.underlaySource?.width&&this.underlaySource?.height) {
        const source=this.underlaySource;
        this.oldContext.setTransform(1,0,0,1,0,0);
        this.oldContext.clearRect(0,0,this.oldSpread.width,this.oldSpread.height);
        this.oldContext.drawImage(source,0,0,source.width,source.height*.25,
          0,0,this.oldSpread.width,this.oldSpread.height);
      }
      ctx.setTransform(1,0,0,1,0,0);ctx.clearRect(0,0,this.film.width,this.film.height);
      // A thin refracting film bends the old print while its contact line dries.
      // Sampling in narrow strips keeps this small patch inexpensive on phones.
      const strength=smooth(this.assets.meta.drying.filmStart,this.assets.meta.drying.start,p);
      for(let y=0;y<this.film.height;y+=2) {
        const offset=(Math.sin(y/r*.052+p*24)+.45*Math.sin(y/r*.119-p*17))*3.4*r*strength;
        const sy=clamp(y+Math.sin(y/r*.035+p*19)*2*r*strength,0,this.oldSpread.height-2);
        ctx.drawImage(this.oldSpread,0,sy,this.oldSpread.width,2,offset,y,this.oldSpread.width,2);
      }
      ctx.setTransform(r,0,0,r,0,0);
      ctx.globalCompositeOperation='source-atop';ctx.fillStyle='rgba(105,220,228,.10)';ctx.fillRect(0,0,w,h*.25);
      ctx.globalCompositeOperation='destination-in';ctx.save();
      if(this.direction<0){ctx.translate(w,0);ctx.scale(-1,1);}
      ctx.drawImage(this.filmMask,0,0,w,h);ctx.restore();ctx.globalCompositeOperation='source-over';
      this.context.drawImage(this.film,0,0,w,this.film.height/r);
      this.context.save();if(this.direction<0){this.context.translate(w,0);this.context.scale(-1,1);}
      this.context.drawImage(this.filmRim,0,0,w,h);this.context.restore();
    }
    draw(p){
      if(this.disposed)return;p=clamp(p);
      const playbackProgress=p;
      // Water, sheet contact and drying must all sample the same retimed instant.
      p=this.simulationProgress(p);
      const box=this.stage.getBoundingClientRect();if(this.width!==box.width||this.height!==box.height)this.resize();
      if(p<this.lastP){this.contact.fill(0);this.lastP=-1;}
      // Packed reveal arrivals remain continuous even when the visible liquid
      // breaks apart. The fallback preserves intervening physical contact.
      const frameStep=1/(this.assets.meta.frameCount-1);
      if(!this.assets.contact)for(let sample=Math.max(0,this.lastP)+frameStep;sample<p;sample+=frameStep)this.stamp(sample,false);
      this.stamp(p,true);this.lastP=p;
      const ctx=this.context,r=this.ratio,w=this.width,h=this.height;
      ctx.setTransform(1,0,0,1,0,0);ctx.clearRect(0,0,this.canvas.width,this.canvas.height);
      ctx.setTransform(r,0,0,r,0,0);
      ctx.fillStyle='#f5ead4';ctx.fillRect(0,0,w,h);
      [...this.spread.querySelectorAll('img')].forEach((img,i)=>{
        const size=Math.min(w*.5/img.naturalWidth,h/img.naturalHeight);
        const iw=img.naturalWidth*size,ih=img.naturalHeight*size;
        ctx.drawImage(img,i*w*.5+(w*.5-iw)*.5,(h-ih)*.5,iw,ih);
      });
      const leftShade=ctx.createLinearGradient(w*.48,0,w*.5,0);
      leftShade.addColorStop(0,'rgba(10,32,36,0)');leftShade.addColorStop(1,'rgba(10,32,36,.19)');
      ctx.fillStyle=leftShade;ctx.fillRect(w*.48,0,w*.02,h);
      const rightShade=ctx.createLinearGradient(w*.5,0,w*.525,0);
      rightShade.addColorStop(0,'rgba(10,32,36,.24)');rightShade.addColorStop(1,'rgba(10,32,36,0)');
      ctx.fillStyle=rightShade;ctx.fillRect(w*.5,0,w*.025,h);
      ctx.save();ctx.globalCompositeOperation='destination-in';
      if(this.direction<0){ctx.translate(w,0);ctx.scale(-1,1);}
      ctx.drawImage(this.wet,0,0,w,h);ctx.restore();
      this.drawFilm(p);
      ctx.save();if(this.direction<0){ctx.translate(w,0);ctx.scale(-1,1);}
      ctx.drawImage(this.fluid,0,0,w,h);ctx.restore();
      this.element.dataset.progress=p.toFixed(4);this.canvas.dataset.progress=p.toFixed(4);
      this.element.dataset.playbackProgress=playbackProgress.toFixed(4);
    }
    commitPages(links){[...this.spread.querySelectorAll('img')].forEach((img,i)=>links[i].replaceChildren(img));}
    dispose(){if(this.disposed)return;this.disposed=true;this.element.remove();this.canvas.width=this.fluid.width=this.wet.width=0;if(this.film){this.film.width=this.filmMask.width=this.filmRim.width=this.oldSpread.width=0;}this.previousPages=[];this.dominantWaves=[];this.underlaySource=null;this.context=null;}
  }
  window.ElMaleconWave=MenuWave;
})();
